name: Base44 Auto Import

on:
  schedule:
    - cron: "0 */6 * * *"   # Toutes les 6 heures
  workflow_dispatch:

jobs:
  run-import:
    runs-on: ubuntu-latest
    steps:
      - name: Appel API Base44
        run: |
          curl -X POST "https://app.base44.com/apps/691b2478e6c5bfcebe5518f3/editor/preview/importsources" \
          -H "Authorization: Bearer immo_hBH7n1NWsSMjbqkUspNPs5iBjf5vPBqD"
